'use strict';
/**
 * Offline-first invoice HTML (mirrors assets/invoices/*.html + bill_pdf_webview).
 * Standalone document with inline CSS — the app caches the string, so preview
 * and share work in airplane mode after first fetch.
 */
function esc(v) {
  return String(v ?? '').replace(/[&<>"']/g, (c) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  })[c]);
}

function inr(n) {
  return '₹' + Number(n || 0).toLocaleString('en-IN');
}

function sealHtml(business) {
  return `<div class="seal"><b>${esc(business.name)}</b><br><span>Authorised Dealer</span></div>`;
}

function standard(bill, items, business, customer, opts) {
  const seal = opts && opts.seal ? sealHtml(business) : '';
  const rows = items
    .map(
      (it, i) =>
        `<tr><td>${i + 1}</td><td>${esc(it.name)}</td><td>${it.qty} ${esc(it.unit)}</td>` +
        `<td>${inr(it.rate)}</td><td>${inr(it.amount)}</td></tr>`
    )
    .join('');
  const sub = items.reduce((s, it) => s + Number(it.amount || 0), 0);
  return `<!DOCTYPE html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Invoice ${esc(bill.invoice_no)}</title>
<style>body{font-family:sans-serif;margin:0;padding:16px;color:#111}
.h{border-bottom:3px solid #0B6B3A;padding-bottom:8px;margin-bottom:12px}
.h h1{margin:0;font-size:22px}.muted{color:#666;font-size:13px}
table{width:100%;border-collapse:collapse;margin:12px 0}
th,td{border:1px solid #ddd;padding:8px;font-size:14px;text-align:left}
th{background:#f2f2f2}.tot{font-size:16px;font-weight:bold}
.right{text-align:right}
.seal{display:inline-block;border:3px double #0B6B3A;color:#0B6B3A;padding:6px 16px;border-radius:12px;text-align:center;font-size:13px;transform:rotate(-8deg);margin-top:16px}</style></head><body>
<div class="h"><h1>${esc(business.name)}</h1>
<div class="muted">${esc(business.category)}${customer ? ' · Billed to: <b>' + esc(customer.name) + '</b>' : ''}</div></div>
<div>Invoice <b>${esc(bill.invoice_no)}</b> · Date ${esc(bill.invoice_date)}</div>
<table><tr><th>#</th><th>Item</th><th>Qty</th><th>Rate</th><th>Amount</th></tr>${rows}</table>
<div class="right">Subtotal: ${inr(sub)}<br>GST: ${inr(bill.total - sub + bill.discount)}<br>
Discount: ${inr(bill.discount)}<br><span class="tot">Total: ${inr(bill.total)}</span>${seal}</div>
<p class="muted">Generated by Khata Clone (college project).</p>
</body></html>`;
}

function thermal(bill, items, business, customer, opts) {
  const seal = opts && opts.seal ? sealHtml(business) : '';
  const rows = items
    .map((it) => `<div>${esc(it.name)}<br><span>${it.qty}x${inr(it.rate)} = <b>${inr(it.amount)}</b></span></div>`)
    .join('<hr>');
  return `<!DOCTYPE html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Receipt ${esc(bill.invoice_no)}</title>
<style>body{font-family:monospace;max-width:300px;margin:0 auto;padding:8px;font-size:13px}
h2{text-align:center;margin:4px 0}hr{border-top:1px dashed #999}.c{text-align:center}
.t{font-size:16px;font-weight:bold}
.seal{border:2px solid #0B6B3A;color:#0B6B3A;display:inline-block;padding:4px 10px;margin-top:10px;font-weight:bold}</style></head><body>
<h2>${esc(business.name)}</h2><div class="c">${esc(bill.invoice_no)} · ${esc(bill.invoice_date)}</div><hr>
${rows}<hr>
<div class="c">Discount ${inr(bill.discount)}<br><span class="t">TOTAL ${inr(bill.total)}</span>${seal}</div>
<div class="c">Thank you!</div></body></html>`;
}

function render(template, bill, items, business, customer, opts) {
  return template === 'thermal'
    ? thermal(bill, items, business, customer, opts)
    : standard(bill, items, business, customer, opts);
}

module.exports = { render, esc, inr };
