#!/bin/bash
# Khata Clone — Oracle Always-Free VM setup (Ubuntu 24.04).
#
# === STATUS: PARKED / ON HOLD ===
# Render is the current (test) host (render.yaml at repo root + docs/05 §0).
# Keep this script in the repo for future self-hosting; do not run it now.
# ================================
#
# Run ONCE on the fresh VM as a sudo-capable user:
#
#   scp khata-backend-deploy.zip <user>@<vm-ip>:~/
#   ssh <user>@<vm-ip>
#   sudo apt install -y unzip
#   unzip -o khata-backend-deploy.zip -d ~/khata-tmp
#   sudo bash ~/khata-tmp/deploy/setup-oracle.sh mykhata.duckdns.org
#
# The script installs Node 22 + Caddy, generates strong secrets, enables
# systemd + HTTPS, and prints the health check. Point your DuckDNS hostname
# at the VM IP *before* running so Caddy can issue the TLS certificate.
set -euo pipefail

DOMAIN="${1:?Usage: sudo bash setup-oracle.sh yourname.duckdns.org}"
APP_USER="${SUDO_USER:-ubuntu}"
APP_HOME="$(eval echo "~$APP_USER")"
APP_DIR="$APP_HOME/khata/backend"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SRC_DIR="$(dirname "$SCRIPT_DIR")"   # khata-backend-deploy.zip root (has src/, package.json)

echo "==> [1/7] Installing Node.js 22 + Caddy + sqlite3"
curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
apt install -y nodejs caddy sqlite3 unzip

echo "==> [2/7] Installing backend to $APP_DIR"
mkdir -p "$APP_DIR"
cp -r "$SRC_DIR/src" "$SRC_DIR/package.json" "$SRC_DIR/package-lock.json" "$SRC_DIR/.env.example" "$APP_DIR/"
mkdir -p "$APP_DIR/data/seed"
cp -r "$SRC_DIR/data/seed/." "$APP_DIR/data/seed/" 2>/dev/null || true
chown -R "$APP_USER:$APP_USER" "$(dirname "$APP_DIR")"

echo "==> [3/7] Installing production dependencies"
sudo -u "$APP_USER" bash -c "cd '$APP_DIR' && npm install --omit=dev"

echo "==> [4/7] Generating secrets (.env)"
JWT_SECRET="$(node -e "console.log(require('crypto').randomBytes(48).toString('base64'))")"
CIPHER_KEY="$(node -e "console.log(require('crypto').randomBytes(48).toString('base64'))")"
cat > "$APP_DIR/.env" <<EOF
# Generated by setup-oracle.sh on $(date -u +%FT%TZ). DO NOT share or commit.
PORT=8080
DB_PATH=./data/khata.db
JWT_SECRET=$JWT_SECRET
CIPHER_KEY=$CIPHER_KEY
ACCESS_EXPIRES=15m
REFRESH_DAYS=30
AUTH_MODE=password
SEED_DEMO=0
EOF
chmod 600 "$APP_DIR/.env"
chown "$APP_USER:$APP_USER" "$APP_DIR/.env"

echo "==> [5/7] Enabling khata systemd service"
sed -e "s#__APP_USER__#$APP_USER#" -e "s#__APP_DIR__#$APP_DIR#" \
  "$SCRIPT_DIR/khata.service" > /etc/systemd/system/khata.service
systemctl daemon-reload
systemctl enable --now khata
sleep 4
systemctl is-active --quiet khata || { echo "khata service failed:"; journalctl -u khata -n 30 --no-pager; exit 1; }

echo "==> [6/7] Enabling Caddy HTTPS for $DOMAIN"
sed -e "s#__DOMAIN__#$DOMAIN#" "$SCRIPT_DIR/Caddyfile" > /etc/caddy/Caddyfile
systemctl reload caddy
sleep 8  # allow TLS issuance on first run

echo "==> [7/7] Health check"
curl -fsS "https://$DOMAIN/health" && echo
echo
echo "DEPLOY OK. Next:"
echo "  1. Phone: install the APK rebuilt with API_BASE_URL=https://$DOMAIN"
echo "  2. Create account (first user), verify no '9999999999' user exists."
echo "  3. Weekly backup cron: 0 2 * * 0 sqlite3 $APP_DIR/data/khata.db \".backup '\$HOME/khata-backup/khata-\$(date +\\%F).db'\""
